services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7711:7711"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - python-runner
    networks:
      - compiler-net

  python-runner:
    image: python:3.9-slim
    command: tail -f /dev/null
    networks:
      - compiler-net

networks:
  compiler-net:
    driver: bridge
